import { defineArrayMember, defineField, defineType } from "sanity";
import { SeoAuditInput } from "../components/SeoAuditInput";

const categories = [
  "AI Voice",
  "Business Automation",
  "Conversion Tracking",
  "CRM & Automation",
  "Lead Generation",
  "Strategy",
];

export const blogPost = defineType({
  name: "blogPost",
  title: "Blog Post",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
    { name: "social", title: "Social" },
    { name: "advanced", title: "Advanced SEO" },
  ],
  fieldsets: [
    { name: "openGraph", title: "Facebook and LinkedIn", options: { collapsible: true, collapsed: false } },
    { name: "twitter", title: "X / Twitter", options: { collapsible: true, collapsed: false } },
    { name: "robots", title: "Robots Directives", options: { collapsible: true, collapsed: false } },
    { name: "previewLimits", title: "Google Preview Limits", options: { collapsible: true, collapsed: true } },
    { name: "redirect", title: "Redirect", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Summary",
      description: "Displayed on the blog index and below the article title.",
      type: "text",
      rows: 4,
      group: "content",
      validation: (rule) => rule.required().min(80).max(320),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      group: "content",
      options: { list: categories, layout: "dropdown" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "string",
      group: "content",
      initialValue: "Vistrow Team",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "publishedAt",
      title: "Publication Date",
      type: "date",
      group: "content",
      options: { dateFormat: "MMMM D, YYYY" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "readTime",
      title: "Reading Time",
      type: "string",
      group: "content",
      initialValue: "5 min read",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "imageBrief",
      title: "Image Brief",
      description: "What to find or create an image of for this post. Editorial note only - not shown on the site.",
      type: "text",
      rows: 2,
      group: "content",
    }),
    defineField({
      name: "imageGenerationPrompt",
      title: "AI Image Generation Prompt",
      description: "Ready to paste into ChatGPT/DALL-E. 16:9 aspect ratio, on-brand colors and style baked in.",
      type: "text",
      rows: 5,
      group: "content",
    }),
    defineField({
      name: "imageAltSuggestion",
      title: "Suggested Alt Text",
      description: "Copy this into the Featured Image's alt text once you've added the image.",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "featuredImage",
      title: "Featured Image",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative Text",
          type: "string",
          validation: (rule) => rule.required(),
        }),
      ],
    }),
    defineField({
      name: "sections",
      title: "Article Sections",
      type: "array",
      group: "content",
      validation: (rule) => rule.required().min(1),
      of: [
        defineArrayMember({
          name: "blogSection",
          title: "Section",
          type: "object",
          fields: [
            defineField({
              name: "heading",
              title: "Heading",
              type: "string",
              description: "Optional for the opening section.",
            }),
            defineField({
              name: "paragraphs",
              title: "Paragraphs",
              type: "array",
              validation: (rule) => rule.required().min(1),
              of: [defineArrayMember({ type: "text", rows: 5 })],
            }),
            defineField({
              name: "points",
              title: "Key Points",
              type: "array",
              of: [defineArrayMember({ type: "string" })],
            }),
          ],
          preview: {
            select: { title: "heading", paragraphs: "paragraphs" },
            prepare({ title, paragraphs }) {
              return {
                title: title || "Opening section",
                subtitle: Array.isArray(paragraphs) ? paragraphs[0] : "",
              };
            },
          },
        }),
      ],
    }),
    defineField({
      name: "seoAudit",
      title: "SEO Analysis",
      type: "string",
      group: "seo",
      readOnly: true,
      components: { input: SeoAuditInput },
    }),
    defineField({
      name: "focusKeyword",
      title: "Focus Keyword",
      description: "The main search phrase this article should rank for.",
      type: "string",
      group: "seo",
      validation: (rule) => rule.custom((value) => value ? true : "Add a focus keyword to activate the full SEO analysis.").warning(),
    }),
    defineField({
      name: "secondaryKeywords",
      title: "Secondary Keywords",
      description: "Related phrases and semantic variations.",
      type: "array",
      group: "seo",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.unique().max(8),
    }),
    defineField({
      name: "metaTitle",
      title: "SEO Title",
      type: "string",
      group: "seo",
      description: "Keep this near 50 to 60 characters.",
      validation: (rule) => rule.required().max(65),
    }),
    defineField({
      name: "metaDescription",
      title: "SEO Description",
      type: "text",
      rows: 3,
      group: "seo",
      description: "Keep this near 140 to 160 characters.",
      validation: (rule) => rule.required().max(170),
    }),
    defineField({
      name: "breadcrumbTitle",
      title: "Breadcrumb Title",
      description: "Optional shorter label used in breadcrumbs.",
      type: "string",
      group: "seo",
      validation: (rule) => rule.max(60),
    }),
    defineField({
      name: "openGraphTitle",
      title: "Social Title",
      type: "string",
      group: "social",
      fieldset: "openGraph",
      description: "Falls back to the SEO title when empty.",
      validation: (rule) => rule.max(95),
    }),
    defineField({
      name: "openGraphDescription",
      title: "Social Description",
      type: "text",
      rows: 3,
      group: "social",
      fieldset: "openGraph",
      description: "Falls back to the SEO description when empty.",
      validation: (rule) => rule.max(200),
    }),
    defineField({
      name: "openGraphImage",
      title: "Social Sharing Image",
      type: "image",
      group: "social",
      fieldset: "openGraph",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alternative Text", type: "string", validation: (rule) => rule.required() }),
      ],
    }),
    defineField({
      name: "twitterCard",
      title: "Card Type",
      type: "string",
      group: "social",
      fieldset: "twitter",
      initialValue: "summary_large_image",
      options: {
        layout: "radio",
        list: [
          { title: "Large image", value: "summary_large_image" },
          { title: "Compact summary", value: "summary" },
        ],
      },
    }),
    defineField({
      name: "twitterTitle",
      title: "X Title",
      type: "string",
      group: "social",
      fieldset: "twitter",
      description: "Falls back to the social title when empty.",
      validation: (rule) => rule.max(70),
    }),
    defineField({
      name: "twitterDescription",
      title: "X Description",
      type: "text",
      rows: 3,
      group: "social",
      fieldset: "twitter",
      description: "Falls back to the social description when empty.",
      validation: (rule) => rule.max(200),
    }),
    defineField({
      name: "twitterImage",
      title: "X Image",
      type: "image",
      group: "social",
      fieldset: "twitter",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alternative Text", type: "string", validation: (rule) => rule.required() }),
      ],
    }),
    defineField({
      name: "canonicalUrl",
      title: "Canonical URL",
      description: "Leave empty to use the article URL automatically.",
      type: "url",
      group: "advanced",
      validation: (rule) => rule.uri({ scheme: ["https"] }),
    }),
    defineField({
      name: "schemaType",
      title: "Article Schema Type",
      type: "string",
      group: "advanced",
      initialValue: "BlogPosting",
      options: {
        layout: "radio",
        list: [
          { title: "Blog Posting", value: "BlogPosting" },
          { title: "Article", value: "Article" },
          { title: "News Article", value: "NewsArticle" },
        ],
      },
    }),
    defineField({
      name: "robotsIndex",
      title: "Allow search engines to index this article",
      type: "boolean",
      group: "advanced",
      fieldset: "robots",
      initialValue: true,
    }),
    defineField({
      name: "robotsFollow",
      title: "Allow search engines to follow links",
      type: "boolean",
      group: "advanced",
      fieldset: "robots",
      initialValue: true,
    }),
    defineField({
      name: "robotsNoArchive",
      title: "Prevent cached copies",
      type: "boolean",
      group: "advanced",
      fieldset: "robots",
      initialValue: false,
    }),
    defineField({
      name: "robotsNoImageIndex",
      title: "Prevent image indexing",
      type: "boolean",
      group: "advanced",
      fieldset: "robots",
      initialValue: false,
    }),
    defineField({
      name: "robotsNoSnippet",
      title: "Prevent text snippets",
      type: "boolean",
      group: "advanced",
      fieldset: "robots",
      initialValue: false,
    }),
    defineField({
      name: "robotsMaxSnippet",
      title: "Maximum Snippet Length",
      description: "Use -1 for no limit.",
      type: "number",
      group: "advanced",
      fieldset: "previewLimits",
      initialValue: -1,
      validation: (rule) => rule.integer().min(-1),
    }),
    defineField({
      name: "robotsMaxVideoPreview",
      title: "Maximum Video Preview",
      description: "Use -1 for no limit.",
      type: "number",
      group: "advanced",
      fieldset: "previewLimits",
      initialValue: -1,
      validation: (rule) => rule.integer().min(-1),
    }),
    defineField({
      name: "robotsMaxImagePreview",
      title: "Maximum Image Preview",
      type: "string",
      group: "advanced",
      fieldset: "previewLimits",
      initialValue: "large",
      options: {
        layout: "radio",
        list: [
          { title: "Large", value: "large" },
          { title: "Standard", value: "standard" },
          { title: "None", value: "none" },
        ],
      },
    }),
    defineField({
      name: "excludeFromSitemap",
      title: "Exclude from XML sitemap",
      type: "boolean",
      group: "advanced",
      initialValue: false,
    }),
    defineField({
      name: "redirectUrl",
      title: "Redirect Destination",
      description: "Optional destination used when this article should redirect elsewhere.",
      type: "url",
      group: "advanced",
      fieldset: "redirect",
      validation: (rule) => rule.uri({ scheme: ["https"] }),
    }),
    defineField({
      name: "redirectPermanent",
      title: "Permanent Redirect",
      description: "Enabled uses a permanent redirect. Disabled uses a temporary redirect.",
      type: "boolean",
      group: "advanced",
      fieldset: "redirect",
      initialValue: true,
      hidden: ({ document }) => !document?.redirectUrl,
    }),
  ],
  orderings: [
    {
      title: "Publication date, newest",
      name: "publishedAtDesc",
      by: [{ field: "publishedAt", direction: "desc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      category: "category",
      date: "publishedAt",
      media: "featuredImage",
    },
    prepare({ title, category, date, media }) {
      return {
        title,
        subtitle: [category, date].filter(Boolean).join(" | "),
        media,
      };
    },
  },
});
