import { defineField, defineType } from "sanity";

// One pre-planned topic from the 30-day content calendar generated by
// /api/cron/generate-calendar. The daily cron consumes these in dayIndex
// order instead of re-deciding a topic each run, which is what previously
// let the model converge back onto a near-duplicate title over time.
export const contentCalendarEntry = defineType({
  name: "contentCalendarEntry",
  title: "Content Calendar Entry",
  type: "document",
  fields: [
    defineField({ name: "dayIndex", title: "Day Index", type: "number", readOnly: true }),
    defineField({ name: "title", title: "Planned Title", type: "string", readOnly: true }),
    defineField({ name: "category", title: "Category", type: "string", readOnly: true }),
    defineField({ name: "focusKeyword", title: "Focus Keyword", type: "string", readOnly: true }),
    defineField({ name: "angle", title: "Angle", type: "text", readOnly: true }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      readOnly: true,
      options: { list: ["pending", "used"] },
    }),
    defineField({ name: "createdAt", title: "Created At", type: "datetime", readOnly: true }),
    defineField({ name: "usedAt", title: "Used At", type: "datetime", readOnly: true }),
    defineField({ name: "blogPostId", title: "Blog Post Doc ID", type: "string", readOnly: true }),
  ],
  preview: {
    select: { title: "title", status: "status", dayIndex: "dayIndex" },
    prepare({ title, status, dayIndex }) {
      return {
        title: `${status === "used" ? "✅" : "🕓"} Day ${dayIndex}: ${title}`,
        subtitle: status,
      };
    },
  },
});
